CREATE TABLE receipt (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    id_shop INT UNSIGNED NOT NULL,
    id_interval INT UNSIGNED NOT NULL,
    data TIMESTAMP NOT NULL DEFAULT NOW(),
    amount DECIMAL (10,2) UNSIGNED NOT NULL,
    bought VARCHAR(6000)
);
